/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsFindByTags } from "../../funcs/petsFindByTags.js";
import { FindPetsByTagsRequest$zodSchema } from "../../models/findpetsbytagsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FindPetsByTagsRequest$zodSchema.optional(),
};

export const tool$petsFindByTags: ToolDefinition<typeof args> = {
  name: "pets-find-by-tags",
  description: `Finds Pets by tags

Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await petsFindByTags(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
