/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsAdd } from "../../funcs/petsAdd.js";
import { Pet$zodSchema } from "../../models/pet.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: Pet$zodSchema.describe(`Create a new pet in the store`),
};

export const tool$petsAdd: ToolDefinition<typeof args> = {
  name: "pets-add",
  description: `Add a new pet to the store

Add a new pet to the store`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await petsAdd(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
