/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsFindByStatus } from "../../funcs/petsFindByStatus.js";
import { FindPetsByStatusRequest$zodSchema } from "../../models/findpetsbystatusop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FindPetsByStatusRequest$zodSchema.optional(),
};

export const tool$petsFindByStatus: ToolDefinition<typeof args> = {
  name: "pets-find-by-status",
  description: `Finds Pets by status

Multiple status values can be provided with comma separated strings`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await petsFindByStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
