/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsGetById } from "../../funcs/petsGetById.js";
import { GetPetByIdRequest$zodSchema } from "../../models/getpetbyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPetByIdRequest$zodSchema,
};

export const tool$petsGetById: ToolDefinition<typeof args> = {
  name: "pets-get-by-id",
  description: `Find pet by ID

Returns a single pet`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await petsGetById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
