/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsUploadImage } from "../../funcs/petsUploadImage.js";
import { UploadFileRequest$zodSchema } from "../../models/uploadfileop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UploadFileRequest$zodSchema,
};

export const tool$petsUploadImage: ToolDefinition<typeof args> = {
  name: "pets-upload-image",
  description: `uploads an image`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await petsUploadImage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
