/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storesOrdersPlace } from "../../funcs/storesOrdersPlace.js";
import { Order$zodSchema } from "../../models/order.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: Order$zodSchema.optional(),
};

export const tool$storesOrdersPlace: ToolDefinition<typeof args> = {
  name: "stores-orders-place",
  description: `Place an order for a pet

Place a new order in the store`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await storesOrdersPlace(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
