/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storeOrdersDelete } from "../../funcs/storeOrdersDelete.js";
import { DeleteOrderRequest$zodSchema } from "../../models/deleteorderop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteOrderRequest$zodSchema,
};

export const tool$storeOrdersDelete: ToolDefinition<typeof args> = {
  name: "store-orders-delete",
  description: `Delete purchase order by ID

For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await storeOrdersDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
