/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storesOrdersGetById } from "../../funcs/storesOrdersGetById.js";
import { GetOrderByIdRequest$zodSchema } from "../../models/getorderbyidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetOrderByIdRequest$zodSchema,
};

export const tool$storesOrdersGetById: ToolDefinition<typeof args> = {
  name: "stores-orders-get-by-id",
  description: `Find purchase order by ID

For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await storesOrdersGetById(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
