/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storesGetInventory } from "../../funcs/storesGetInventory.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$storesGetInventory: ToolDefinition = {
  name: "stores-get-inventory",
  description: `Returns pet inventories by status

Returns a map of status codes to quantities`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await storesGetInventory(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
