/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersCreate } from "../../funcs/usersCreate.js";
import { User$zodSchema } from "../../models/user.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: User$zodSchema.optional().describe(`Created user object`),
};

export const tool$usersCreate: ToolDefinition<typeof args> = {
  name: "users-create",
  description: `Create user

This can only be done by the logged in user.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await usersCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
