/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersLogin } from "../../funcs/usersLogin.js";
import { LoginUserRequest$zodSchema } from "../../models/loginuserop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LoginUserRequest$zodSchema.optional(),
};

export const tool$usersLogin: ToolDefinition<typeof args> = {
  name: "users-login",
  description: `Logs user into the system`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await usersLogin(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
