/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersDelete } from "../../funcs/usersDelete.js";
import { DeleteUserRequest$zodSchema } from "../../models/deleteuserop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteUserRequest$zodSchema,
};

export const tool$usersDelete: ToolDefinition<typeof args> = {
  name: "users-delete",
  description: `Delete user

This can only be done by the logged in user.`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await usersDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
