/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersUpdate } from "../../funcs/usersUpdate.js";
import { UpdateUserRequest$zodSchema } from "../../models/updateuserop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateUserRequest$zodSchema,
};

export const tool$usersUpdate: ToolDefinition<typeof args> = {
  name: "users-update",
  description: `Update user

This can only be done by the logged in user.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await usersUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
