/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersGetByName } from "../../funcs/usersGetByName.js";
import { GetUserByNameRequest$zodSchema } from "../../models/getuserbynameop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetUserByNameRequest$zodSchema,
};

export const tool$usersGetByName: ToolDefinition<typeof args> = {
  name: "users-get-by-name",
  description: `Get user by user name`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await usersGetByName(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
