/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { usersCreateWithList } from "../../funcs/usersCreateWithList.js";
import { User$zodSchema } from "../../models/user.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.array(User$zodSchema).optional(),
};

export const tool$usersCreateWithList: ToolDefinition<typeof args> = {
  name: "users-create-with-list",
  description: `Creates list of users with given input array

Creates list of users with given input array`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await usersCreateWithList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
