/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { PetstoreCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import {
  createRegisterTool,
  MCPToolAnnotationFilter,
  registerDynamicTools,
} from "./tools.js";
import { tool$petsAdd } from "./tools/petsAdd.js";
import { tool$petsDelete } from "./tools/petsDelete.js";
import { tool$petsFindByStatus } from "./tools/petsFindByStatus.js";
import { tool$petsFindByTags } from "./tools/petsFindByTags.js";
import { tool$petsGetById } from "./tools/petsGetById.js";
import { tool$petsUpdate } from "./tools/petsUpdate.js";
import { tool$petsUploadImage } from "./tools/petsUploadImage.js";
import { tool$storeOrdersDelete } from "./tools/storeOrdersDelete.js";
import { tool$storesGetInventory } from "./tools/storesGetInventory.js";
import { tool$storesOrdersGetById } from "./tools/storesOrdersGetById.js";
import { tool$storesOrdersPlace } from "./tools/storesOrdersPlace.js";
import { tool$usersCreate } from "./tools/usersCreate.js";
import { tool$usersCreateWithList } from "./tools/usersCreateWithList.js";
import { tool$usersDelete } from "./tools/usersDelete.js";
import { tool$usersGetByName } from "./tools/usersGetByName.js";
import { tool$usersLogin } from "./tools/usersLogin.js";
import { tool$usersLogout } from "./tools/usersLogout.js";
import { tool$usersUpdate } from "./tools/usersUpdate.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  annotationFilter?: MCPToolAnnotationFilter | undefined;
  getSDK?: () => PetstoreCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
  environment?: SDKOptions["environment"] | undefined;
}) {
  const server = new McpServer({
    name: "Petstore",
    version: "0.1.1",
  });

  const getClient = deps.getSDK || (() =>
    new PetstoreCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      environment: deps.environment,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
    deps.annotationFilter,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$petsUpdate);
  tool(tool$petsAdd);
  tool(tool$petsFindByStatus);
  tool(tool$petsFindByTags);
  tool(tool$petsGetById);
  tool(tool$petsDelete);
  tool(tool$petsUploadImage);
  tool(tool$storesGetInventory);
  tool(tool$storesOrdersPlace);
  tool(tool$storesOrdersGetById);
  tool(tool$storeOrdersDelete);
  tool(tool$usersCreate);
  tool(tool$usersCreateWithList);
  tool(tool$usersLogin);
  tool(tool$usersLogout);
  tool(tool$usersGetByName);
  tool(tool$usersUpdate);
  tool(tool$usersDelete);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
