/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Not Found error
 */
export type ApiErrorInvalidInput = { status: number; error: string };

export const ApiErrorInvalidInput$zodSchema: z.ZodType<ApiErrorInvalidInput> = z
  .object({
    error: z.string(),
    status: z.int(),
  }).describe("Not Found error");
