/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { Pet, Pet$zodSchema } from "./pet.js";

export type DeletePetRequest = { api_key?: string | undefined; petId: number };

export const DeletePetRequest$zodSchema: z.ZodType<DeletePetRequest> = z.object(
  {
    api_key: z.string().optional(),
    petId: z.int().describe("Pet id to delete"),
  },
);

export type DeletePetResponse =
  | ApiErrorNotFound
  | Pet
  | ApiErrorInvalidInput
  | ApiErrorUnauthorized;

export const DeletePetResponse$zodSchema: z.ZodType<DeletePetResponse> = z
  .union([
    ApiErrorNotFound$zodSchema,
    Pet$zodSchema,
    ApiErrorInvalidInput$zodSchema,
    ApiErrorUnauthorized$zodSchema,
  ]);
