/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { User, User$zodSchema } from "./user.js";

export type DeleteUserRequest = { username: string };

export const DeleteUserRequest$zodSchema: z.ZodType<DeleteUserRequest> = z
  .object({
    username: z.string().describe("The name that needs to be deleted"),
  });

export type DeleteUserResponse =
  | ApiErrorNotFound
  | ApiErrorInvalidInput
  | ApiErrorUnauthorized
  | User;

export const DeleteUserResponse$zodSchema: z.ZodType<DeleteUserResponse> = z
  .union([
    ApiErrorNotFound$zodSchema,
    ApiErrorInvalidInput$zodSchema,
    ApiErrorUnauthorized$zodSchema,
    User$zodSchema,
  ]);
