/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { Order, Order$zodSchema } from "./order.js";

export type DeleteOrderRequest = { orderId: number };

export const DeleteOrderRequest$zodSchema: z.ZodType<DeleteOrderRequest> = z
  .object({
    orderId: z.int().describe("ID of the order that needs to be deleted"),
  });

export type DeleteOrderResponse =
  | ApiErrorNotFound
  | ApiErrorInvalidInput
  | ApiErrorUnauthorized
  | Order;

export const DeleteOrderResponse$zodSchema: z.ZodType<DeleteOrderResponse> = z
  .union([
    ApiErrorNotFound$zodSchema,
    ApiErrorInvalidInput$zodSchema,
    ApiErrorUnauthorized$zodSchema,
    Order$zodSchema,
  ]);
