/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { Pet, Pet$zodSchema } from "./pet.js";

/**
 * Status values that need to be considered for filter
 */
export const FindPetsByStatusStatus = {
  Available: "available",
  Pending: "pending",
  Sold: "sold",
} as const;
/**
 * Status values that need to be considered for filter
 */
export type FindPetsByStatusStatus = ClosedEnum<typeof FindPetsByStatusStatus>;

export const FindPetsByStatusStatus$zodSchema = z.enum([
  "available",
  "pending",
  "sold",
]).describe("Status values that need to be considered for filter");

export type FindPetsByStatusRequest = {
  status?: FindPetsByStatusStatus | undefined;
};

export const FindPetsByStatusRequest$zodSchema: z.ZodType<
  FindPetsByStatusRequest
> = z.object({
  status: FindPetsByStatusStatus$zodSchema.default("available").describe(
    "Status values that need to be considered for filter",
  ),
});

export type FindPetsByStatusResponse =
  | ApiErrorNotFound
  | ApiErrorInvalidInput
  | ApiErrorUnauthorized
  | Array<Pet>;

export const FindPetsByStatusResponse$zodSchema: z.ZodType<
  FindPetsByStatusResponse
> = z.union([
  ApiErrorNotFound$zodSchema,
  ApiErrorInvalidInput$zodSchema,
  ApiErrorUnauthorized$zodSchema,
  z.array(Pet$zodSchema).describe("successful operation"),
]);
