/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { Pet, Pet$zodSchema } from "./pet.js";

export type FindPetsByTagsRequest = { tags?: Array<string> | undefined };

export const FindPetsByTagsRequest$zodSchema: z.ZodType<FindPetsByTagsRequest> =
  z.object({
    tags: z.array(z.string()).describe("Tags to filter by").optional(),
  });

export type FindPetsByTagsResponse =
  | ApiErrorNotFound
  | ApiErrorInvalidInput
  | ApiErrorUnauthorized
  | Array<Pet>;

export const FindPetsByTagsResponse$zodSchema: z.ZodType<
  FindPetsByTagsResponse
> = z.union([
  ApiErrorNotFound$zodSchema,
  ApiErrorInvalidInput$zodSchema,
  ApiErrorUnauthorized$zodSchema,
  z.array(Pet$zodSchema).describe("successful operation"),
]);
