/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";

export type GetInventoryResponse = ApiErrorNotFound | ApiErrorUnauthorized | {
  [k: string]: number;
};

export const GetInventoryResponse$zodSchema: z.ZodType<GetInventoryResponse> = z
  .union([
    ApiErrorNotFound$zodSchema,
    ApiErrorUnauthorized$zodSchema,
    z.record(z.string(), z.int()).describe("successful operation"),
  ]);
