/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { Order, Order$zodSchema } from "./order.js";

export type GetOrderByIdRequest = { orderId: number };

export const GetOrderByIdRequest$zodSchema: z.ZodType<GetOrderByIdRequest> = z
  .object({
    orderId: z.int().describe("ID of order that needs to be fetched"),
  });

export type GetOrderByIdResponse =
  | ApiErrorNotFound
  | ApiErrorInvalidInput
  | ApiErrorUnauthorized
  | Order;

export const GetOrderByIdResponse$zodSchema: z.ZodType<GetOrderByIdResponse> = z
  .union([
    ApiErrorNotFound$zodSchema,
    ApiErrorInvalidInput$zodSchema,
    ApiErrorUnauthorized$zodSchema,
    Order$zodSchema,
  ]);
