/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { Pet, Pet$zodSchema } from "./pet.js";

export type GetPetByIdRequest = { petId: number };

export const GetPetByIdRequest$zodSchema: z.ZodType<GetPetByIdRequest> = z
  .object({
    petId: z.int().describe("ID of pet to return"),
  });

export type GetPetByIdResponse =
  | ApiErrorNotFound
  | Pet
  | ApiErrorInvalidInput
  | ApiErrorUnauthorized;

export const GetPetByIdResponse$zodSchema: z.ZodType<GetPetByIdResponse> = z
  .union([
    ApiErrorNotFound$zodSchema,
    Pet$zodSchema,
    ApiErrorInvalidInput$zodSchema,
    ApiErrorUnauthorized$zodSchema,
  ]);
