/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { User, User$zodSchema } from "./user.js";

export type GetUserByNameRequest = { username: string };

export const GetUserByNameRequest$zodSchema: z.ZodType<GetUserByNameRequest> = z
  .object({
    username: z.string().describe(
      "The name that needs to be fetched. Use user1 for testing. ",
    ),
  });

export type GetUserByNameResponse =
  | ApiErrorNotFound
  | ApiErrorInvalidInput
  | ApiErrorUnauthorized
  | User;

export const GetUserByNameResponse$zodSchema: z.ZodType<GetUserByNameResponse> =
  z.union([
    ApiErrorNotFound$zodSchema,
    ApiErrorInvalidInput$zodSchema,
    ApiErrorUnauthorized$zodSchema,
    User$zodSchema,
  ]);
