/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorInvalidInput,
  ApiErrorInvalidInput$zodSchema,
} from "./apierrorinvalidinput.js";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";

export type LoginUserRequest = {
  username?: string | undefined;
  password?: string | undefined;
};

export const LoginUserRequest$zodSchema: z.ZodType<LoginUserRequest> = z.object(
  {
    password: z.string().describe("The password for login in clear text")
      .optional(),
    username: z.string().describe("The user name for login").optional(),
  },
);

export type LoginUserResponseResult =
  | ApiErrorNotFound
  | ApiErrorInvalidInput
  | ApiErrorUnauthorized
  | string;

export const LoginUserResponseResult$zodSchema: z.ZodType<
  LoginUserResponseResult
> = z.union([
  ApiErrorNotFound$zodSchema,
  ApiErrorInvalidInput$zodSchema,
  ApiErrorUnauthorized$zodSchema,
  z.string().describe("successful operation"),
]);

export type LoginUserResponse = {
  Headers: { [k: string]: Array<string> };
  Result:
    | ApiErrorNotFound
    | ApiErrorInvalidInput
    | ApiErrorUnauthorized
    | string;
};

export const LoginUserResponse$zodSchema: z.ZodType<LoginUserResponse> = z
  .object({
    Headers: z.record(z.string(), z.array(z.string())).default({}),
    Result: z.union([
      ApiErrorNotFound$zodSchema,
      ApiErrorInvalidInput$zodSchema,
      ApiErrorUnauthorized$zodSchema,
      z.string().describe("successful operation"),
    ]),
  });
