/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Order Status
 */
export const OrderStatus = {
  Placed: "placed",
  Approved: "approved",
  Delivered: "delivered",
} as const;
/**
 * Order Status
 */
export type OrderStatus = ClosedEnum<typeof OrderStatus>;

export const OrderStatus$zodSchema = z.enum([
  "placed",
  "approved",
  "delivered",
]).describe("Order Status");

export type Order = {
  id?: number | undefined;
  petId?: number | undefined;
  quantity?: number | undefined;
  shipDate?: string | undefined;
  status?: OrderStatus | undefined;
  complete?: boolean | undefined;
};

export const Order$zodSchema: z.ZodType<Order> = z.object({
  complete: z.boolean().optional(),
  id: z.int().optional(),
  petId: z.int().optional(),
  quantity: z.int().optional(),
  shipDate: z.iso.datetime({ offset: true }).optional(),
  status: OrderStatus$zodSchema.optional().describe("Order Status"),
});
