/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApiErrorNotFound,
  ApiErrorNotFound$zodSchema,
} from "./apierrornotfound.js";
import {
  ApiErrorUnauthorized,
  ApiErrorUnauthorized$zodSchema,
} from "./apierrorunauthorized.js";
import { Order, Order$zodSchema } from "./order.js";

export type PlaceOrderResponse =
  | ApiErrorNotFound
  | ApiErrorUnauthorized
  | Order;

export const PlaceOrderResponse$zodSchema: z.ZodType<PlaceOrderResponse> = z
  .union([
    ApiErrorNotFound$zodSchema,
    ApiErrorUnauthorized$zodSchema,
    Order$zodSchema,
  ]);
