/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { User, User$zodSchema } from "./user.js";

export type UpdateUserRequest = { username: string; body?: User | undefined };

export const UpdateUserRequest$zodSchema: z.ZodType<UpdateUserRequest> = z
  .object({
    body: User$zodSchema.optional().describe(
      "Update an existent user in the store",
    ),
    username: z.string().describe("name that needs to be updated"),
  });
