/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";

export type UploadFileRequest = {
  petId: number;
  additionalMetadata?: string | undefined;
  body?: Uint8Array | string | undefined;
};

export const UploadFileRequest$zodSchema: z.ZodType<UploadFileRequest> = z
  .object({
    additionalMetadata: z.string().describe("Additional Metadata").optional(),
    body: z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ).optional(),
    petId: z.int().describe("ID of pet to update"),
  });
